### ISSUE TITLE
Problems with Tensorflow Object Detection API

### ISSUE THREAD

**Issue by sepi83** [ARM-software/Tool-Solutions#142]
Is there any "ready packages" for the objects detection API  on Arm64 ? I did install all need stuff and performed steps on your Docker image, but I am getting following errors:

`2022-08-04 16:58:51.293759: I tensorflow/core/util/util.cc:175] Experimental oneDNN custom operations are on. If you experience issues, please turn them off by setting the environment variable TF_ENABLE_ONEDNN_OPTS=0.
/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/models/research/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 35, in <module>
    from official.legacy.image_classification.efficientnet import efficientnet_model
ModuleNotFoundError: No module named 'official.legacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 20, in <module>
    from object_detection.builders import model_builder
  File "/home/ubuntu/tensorflow/models/research/object_detection/builders/model_builder.py", line 70, in <module>
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "/home/ubuntu/tensorflow/models/research/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 37, in <module>
    from official.vision.image_classification.efficientnet import efficientnet_model
  File "/home/ubuntu/python3-venv/lib/python3.8/site-packages/official/vision/image_classification/efficientnet/efficientnet_model.py", line 37, in <module>
    from official.vision.image_classification import preprocessing
  File "/home/ubuntu/python3-venv/lib/python3.8/site-packages/official/vision/image_classification/preprocessing.py", line 25, in <module>
    from official.vision.image_classification import augment
  File "/home/ubuntu/python3-venv/lib/python3.8/site-packages/official/vision/image_classification/augment.py", line 31, in <module>
    from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops
ModuleNotFoundError: No module named 'tensorflow.python.keras.layers.preprocessing'
(python3-venv) ubuntu@fb9da9f9bef0:~/tensorflow/models/research$ python object_detection/builders/model_builder_test.py
2022-08-04 17:41:25.737320: I tensorflow/core/util/util.cc:175] Experimental oneDNN custom operations are on. If you experience issues, please turn them off by setting the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/home/ubuntu/python3-venv/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/models/research/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 35, in <module>
    from official.legacy.image_classification.efficientnet import efficientnet_model
ModuleNotFoundError: No module named 'official.legacy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 20, in <module>
    from object_detection.builders import model_builder
  File "/home/ubuntu/tensorflow/models/research/object_detection/builders/model_builder.py", line 70, in <module>
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "/home/ubuntu/tensorflow/models/research/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 37, in <module>
    from official.vision.image_classification.efficientnet import efficientnet_model
  File "/home/ubuntu/python3-venv/lib/python3.8/site-packages/official/vision/image_classification/efficientnet/efficientnet_model.py", line 37, in <module>
    from official.vision.image_classification import preprocessing
  File "/home/ubuntu/python3-venv/lib/python3.8/site-packages/official/vision/image_classification/preprocessing.py", line 25, in <module>
    from official.vision.image_classification import augment
  File "/home/ubuntu/python3-venv/lib/python3.8/site-packages/official/vision/image_classification/augment.py", line 31, in <module>
    from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_ops
ModuleNotFoundError: No module named 'tensorflow.python.keras.layers.preprocessing`

I get similar error messages also on MacBook Air M1.

**Comment by nSircombe** [comment]
HI @sepi83 

Would you be able to provide a step-by-step reproducer for the above error please? As well as details of the platform you're running on (Note: these docker builds are not intended for Apple silicon and MacOS).

**Comment by sepi83** [comment]
More information:

- MacBook Air 2020 M1, MacOs Ventura 13.0 beta
- Docker 4.11.0
- Doker engine v20.10.17
- Docker image armswdev/tensorflow-arm-neoverse:latest
- Installed Tensorflow Object Detection API with the guide from here https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html
- Tested the installation python object_detection/builders/model_builder_test.py

Side note:

- Installed the API also on my MacBook
- Tested my installation with this https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/auto_examples/plot_object_detection_checkpoint.html#sphx-glr-auto-examples-plot-object-detection-checkpoint-py on Jupyter notebook on Visual Studio Code
-Got a similar error message related to libtensorflow_io_plugins.so
- The code works if I do run everything again without restarting the kernel

**Comment by nSircombe** [comment]
Hi @sepi83,

I'm afraid these Docker builds are not intended for MacOS, only `arch=aarch64` is supported at present (i.e. not `aarch=arm64`), https://github.com/ARM-software/Tool-Solutions/blob/0442ee9ba8fae866f5969e5855ed87e17e62a50c/docker/tensorflow-aarch64/build.sh#L79-L85

You may be better off looking at the tensorflow-macos wheel on pypi and/or raising any issues on the main TensorFlow GitHub project - https://github.com/tensorflow/tensorflow.

Sorry we can't be of more assistance in this case.
