### ISSUE TITLE
scipy build error: apple m1 - arm64 try to build tensorflow with docker 

### ISSUE THREAD

**Issue by jiaqiwang969** [ARM-software/Tool-Solutions#46]
Driven by curiosity, I am trying to build arm64- tensorflow with dockerfile, in apple m1 scilicon.
The error occurs when build scipy.

with command:
`sudo ./build.sh --build-type tensorflow --tf_version 1 --jobs 4
`
[build-tfv1.log](https://github.com/ARM-software/Tool-Solutions/files/5940894/build-tfv1.log)

```
#39 257.8                  from scipy/sparse/sparsetools/sparsetools.cxx:34:
#39 257.8 /home/ubuntu/python3-venv/lib/python3.7/site-packages/numpy-1.17.1-py3.7-linux-aarch64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
#39 257.8    17 | #warning "Using deprecated NumPy API, disable it with " \
#39 257.8       |  ^~~~~~~
#39 258.2 g++: scipy/sparse/sparsetools/other.cxx
#39 258.2 In file included from /home/ubuntu/python3-venv/lib/python3.7/site-packages/numpy-1.17.1-py3.7-linux-aarch64.egg/numpy/core/include/numpy/ndarraytypes.h:1830,
#39 258.2                  from /home/ubuntu/python3-venv/lib/python3.7/site-packages/numpy-1.17.1-py3.7-linux-aarch64.egg/numpy/core/include/numpy/ndarrayobject.h:12,
#39 258.2                  from scipy/sparse/sparsetools/sparsetools.h:5,
#39 258.2                  from scipy/sparse/sparsetools/other.cxx:4:
#39 258.2 /home/ubuntu/python3-venv/lib/python3.7/site-packages/numpy-1.17.1-py3.7-linux-aarch64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
#39 258.2    17 | #warning "Using deprecated NumPy API, disable it with " \
#39 258.2       |  ^~~~~~~
#39 849.7 g++: fatal error: Killed signal terminated program cc1plus
#39 849.7 compilation terminated.
#39 885.2 Running from scipy source directory.
#39 885.2 /home/ubuntu/python3-venv/lib/python3.7/site-packages/numpy-1.17.1-py3.7-linux-aarch64.egg/numpy/distutils/system_info.py:782: UserWarning: Specified path /home/ubuntu/python3-venv/include/python3.7m is invalid.
#39 885.2   return self.get_paths(self.section, key)
#39 885.2 /home/ubuntu/python3-venv/lib/python3.7/site-packages/numpy-1.17.1-py3.7-linux-aarch64.egg/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/include/python3.7m is invalid.
#39 885.2   return self.get_paths(self.section, key)
#39 885.3 error: Command "g++ -DNDEBUG -g -fwrapv -O3 -Wall -mcpu=native -moutline-atomics -O3 -fPIC -D__STDC_FORMAT_MACROS=1 -Iscipy/sparse/sparsetools -I/home/ubuntu/python3-venv/lib/python3.7/site-packages/numpy-1.17.1-py3.7-linux-aarch64.egg/numpy/core/include -I/home/ubuntu/python3-venv/include -I/usr/local/include/python3.7m -c scipy/sparse/sparsetools/bsr.cxx -o build/temp.linux-aarch64-3.7/scipy/sparse/sparsetools/bsr.o -MMD -MF build/temp.linux-aarch64-3.7/scipy/sparse/sparsetools/bsr.o.d" failed with exit status 1
#39 ERROR: executor failed running [/bin/sh -c $PACKAGE_DIR/build-scipy.sh]: exit code: 1
------
 > [tensorflow-tools 12/19] RUN /home/ubuntu//packages/build-scipy.sh:
------
executor failed running [/bin/sh -c $PACKAGE_DIR/build-scipy.sh]: exit code: 1
```

**Comment by nSircombe** [comment]
Hi @jiaqiwang969,

Thanks for your interest. At present these scripts are primarily intended for Linux environments running on Neoverse-N1 hardware, and have not been tested on Apple Silicon.

Looking at the log you've attached, three things spring to mind:
1. The NumPy install doesn't appear to have been entirely successful, you could try replacing the build-from-src `build-numpy.sh` with a simple `pip install numpy`.
2. You should be able to build TF without SciPy, so commenting out the line in the `Dockerfile` which runs `build-scipy.sh` may allow the build to progress further.
3. There is an experimental variant of TensorFlow 2.4 intended for Apple Silicon available: https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html, https://github.com/apple/tensorflow_macos.

Hope that's of some help!

**Comment by jiaqiwang969** [comment]
Hi, @nSircombe 
Thanks for your help. My wish is to build TensorFlow in the 1.5 version, in apple m1- arm64. I know the TensorFlow 2.4 have be available in GitHub., but it not suitable for me.

Until now, I have overcome the above error, it is by memory issue. From resetting and enlarging the docker memory, it passed.
Move on,  TensorFlow tools, base, and lib could be successfully built in Apple m1; The Bazel has also built.

Finally, the step is to build TensorFlow with the file "build-tensorflow.sh"

The biggest issue is the link to package website could not be accessed.

_"https://**mirror.bazel.build**/github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz" is not acessed but "github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz" -- the file could be download._



```
#59 575.7 Analyzing: target //tensorflow/tools/pip_package:build_pip_package (391 packages loaded, 19714 targets configured)
#59 630.7 Analyzing: target //tensorflow/tools/pip_package:build_pip_package (391 packages loaded, 19714 targets configured)
#59 693.9 Analyzing: target //tensorflow/tools/pip_package:build_pip_package (391 packages loaded, 19714 targets configured)
#59 766.5 Analyzing: target //tensorflow/tools/pip_package:build_pip_package (391 packages loaded, 19714 targets configured)
#59 849.9 Analyzing: target //tensorflow/tools/pip_package:build_pip_package (391 packages loaded, 19714 targets configured)
#59 945.9 Analyzing: target //tensorflow/tools/pip_package:build_pip_package (391 packages loaded, 19714 targets configured)
#59 1034.8 INFO: Call stack for the definition of repository 'llvm' which is a tf_http_archive (rule definition at /home/ubuntu/packages/tensorflow/third_party/repo.bzl:124:19):
#59 1034.8  - /home/ubuntu/packages/tensorflow/tensorflow/workspace.bzl:547:5
#59 1034.8  - /home/ubuntu/packages/tensorflow/WORKSPACE:19:1
#59 1034.8 WARNING: Download from https://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
#59 1034.8 WARNING: Download from https://github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz failed: class java.io.IOException Premature EOF
#59 1034.8 ERROR: An error occurred during the fetch of repository 'llvm':
#59 1034.8    java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz, https://github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz] to /home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/external/llvm/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz: Premature EOF
#59 1034.9 ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/external/local_config_mlir/BUILD:35:1: @local_config_mlir//:IR depends on @llvm//:support in repository @llvm which failed to fetch. no such package '@llvm//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz, https://github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz] to /home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/external/llvm/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz: Premature EOF
#59 1034.9 ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@llvm//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz, https://github.com/llvm-mirror/llvm/archive/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz] to /home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/external/llvm/7a7e03f906aada0cf4b749b51213fe5784eeff84.tar.gz: Premature EOF
#59 1034.9 INFO: Elapsed time: 824.999s
#59 1034.9 INFO: 0 processes.
#59 1034.9 FAILED: Build did NOT complete successfully (391 packages loaded, 19714 targets configured)
#59 1034.9 FAILED: Build did NOT complete successfully (391 packages loaded, 19714 targets configured)
#59 ERROR: executor failed running [/bin/sh -c $PACKAGE_DIR/build-tensorflow.sh]: exit code: 1
```

Still in the log, there are quite a lot of warnings. I am not sure it could be ignore or not. Some of it also because of the wrong web links.

```
#59 570.9 WARNING: Download from https://mirror.bazel.build/github.com/pybind/pybind11/archive/v2.3.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
#59 571.2 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:647:12: in srcs attribute of cc_library rule //tensorflow/core:lib_proto_parsing: please do not import '//tensorflow/core/platform:protobuf.cc' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.2 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:1093:12: in srcs attribute of cc_library rule //tensorflow/core:framework_lite: please do not import '//tensorflow/core/platform:default/integral_types.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.2 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:1093:12: in srcs attribute of cc_library rule //tensorflow/core:framework_lite: please do not import '//tensorflow/core/platform:default/mutex.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.2 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:1093:12: in srcs attribute of cc_library rule //tensorflow/core:framework_lite: please do not import '//tensorflow/core/platform:default/mutex_data.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.2 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:1091:1: in linkstatic attribute of cc_library rule //tensorflow/core:framework_lite: setting 'linkstatic=1' is recommended if there are no object files
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:abi.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:byte_order.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:context.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:cord.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:cpu_feature_guard.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:cpu_info.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:cuda_libdevice_path.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:demangle.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:denormal.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:dynamic_annotations.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:env.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:env_time.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:error.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:file_statistics.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:file_system.h' directly. You should either move the file to this package or depend on an appropriate rule there
#59 571.6 WARNING: /home/ubuntu/packages/tensorflow/tensorflow/core/BUILD:2455:12: in srcs attribute of cc_library rule //tensorflow/core:lib_internal_impl: please do not import '//tensorflow/core/platform:file_system_helper.h' directly. You should either move the file to this package or depend on an appropriate rule there
```

[build-tfv1.log](https://github.com/ARM-software/Tool-Solutions/files/5950029/build-tfv1.log)

**Comment by jiaqiwang969** [comment]
Further report error when build tensorflow:

ERROR: /home/ubuntu/packages/tensorflow/tensorflow/BUILD:829:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1)
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 676, in <module>
    main()
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 655, in main
    importlib.import_module(package)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/lite/python/lite.py", line 31, in <module>
    from tensorflow.lite.experimental.microfrontend.python.ops import audio_microfrontend_op  # pylint: disable=unused-import
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/lite/experimental/microfrontend/python/ops/audio_microfrontend_op.py", line 30, in <module>
    resource_loader.get_path_to_datafile("_audio_microfrontend_op.so"))
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/3083553ad2d6c5e705de8a2de81b65f3/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_1_tf_python_api_gen_v1.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 78, in load_op_library
    exec(wrappers, module.__dict__)
  File "<string>", line 32
    def audio_microfrontend(audio, sample_rate=16000, window_size=25, window_step=10, num_channels=32, upper_band_limit=, lower_band_limit=, smoothing_bits=10, even_smoothing=, odd_smoothing=, min_signal_remaining=, enable_pcan=False, pcan_strength=, pcan_offset=, gain_bits=21, enable_log=True, scale_shift=6, left_context=0, right_context=0, frame_stride=1, zero_padding=False, out_scale=1, out_type=_dtypes.uint16, name=None):
                                                                                                                        ^
SyntaxError: invalid syntax
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 16.487s, Critical Path: 2.78s
INFO: 7 processes: 7 local.
FAILED: Build did NOT complete successfully

**Comment by nSircombe** [comment]
> My wish is to build TensorFlow in the 1.5 version

I have recently had some other reports of issues with the 1.5 build script - although we moved focus to 2.x some time ago, the 1.x build _should_ still be working - I will look into it, make sure any fixes needed to build on our systems are upstreamed, and let you know. This won't, however, include any testing on an m1 system, but may still be of some help with what you're trying to do.

**Comment by nSircombe** [comment]
Just to note that a working TF 1.x build is tagged here: https://github.com/ARM-software/Tool-Solutions/tree/tensorflow-v1-aarch64
